image: ruby:2.3

cache:
  paths:
  - vendor

before_script:
  - gem install bundler

pages:
  stage: deploy
  script:
  - bundle install --path=vendor/
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
    - master

pages-dev:
  stage: test
  script:
  - bundle install --path=vendor/
  - bundle exec jekyll build -d public-dev
  artifacts:
    paths:
    - public-dev
  except:
    - master
