
title: Alex Ionescu
url: 'https://alexionescu.net'
baseurl: '' #change it according to your repository name


style: styles-3

include: [".well-known"]

#Profile information
name: Alex Ionescu
tagline: Security Engineer
pic: profile.jpg

#sidebar links
email: info@alexionescu.net
#phone: 
website: alexionescu.net
linkedin: ionescualex
github: alexionescu
bitbucket: alexionescu
gitlab: alexionescu
#twitter: ''
